name: skibble_accessibility
description: "A new Flutter project to improve the accessibility of the Skibble app"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  google_sign_in: ^6.1.4
  share_plus: ^7.0.2

  #maps
  #  mapbox_maps_flutter: ^0.4.1
  #  mapbox_maps_flutter: ^0.4.4
  mapbox_maps_flutter: ^0.5.0
  #  flutter_map: ^3.1.0
  flutter_map: ^5.0.0
  #  vector_map_tiles: ^3.1.4
  vector_map_tiles: ^6.0.0
  #  latlong2: ^0.8.1
  latlong2: ^0.9.0
  #  vector_tile_renderer: ^3.0.4
  vector_tile_renderer: ^5.0.1

  #  rolling_switch: ^0.0.2
  animated_switch: ^0.0.2
  flutter_cupertino_datetime_picker: ^3.0.0
  #  sliding_up_panel: ^2.0.0+1
  sliding_up_panel2: ^3.3.0+1
  material_floating_search_bar_2: ^0.5.0
  #  mapbox_gl: ^0.16.0
  hidable: ^1.0.4

  #  firebase_crashlytics: ^2.8.6

  ###Firebase New
  firebase_core: ^2.22.0

  firebase_dynamic_links: ^5.0.16
  cloud_firestore: ^4.13.0
  cloud_functions: ^4.3.4
  firebase_storage: ^11.5.0
  firebase_auth: ^4.13.0
  firebase_messaging: ^14.7.4
  firebase_crashlytics: ^3.4.4
  provider: ^6.0.0

  flutter_secure_storage: ^8.0.0
  package_info_plus: ^5.0.1
  #  Notifications
  #  awesome_notifications: ^0.7.4+1
  awesome_notifications: ^0.8.3

  feedback: ^2.6.0

  image_cropper: ^5.0.0
  intrinsic_dimension: ^0.3.0
  easy_stepper: ^0.7.3
  camerawesome: ^1.0.0-rc2
  flutter_image_compress: ^1.1.0
  galleryimage: ^1.2.0
  cached_network_image: ^3.2.2
  fraction: ^4.1.2
  better_open_file: ^3.6.4
  camera: ^0.10.0

  flutter_cache_manager: ^3.1.2
  file_picker: ^5.2.6
  video_player: ^2.7.2

  video_thumbnail: ^0.5.0
  image_picker: ^1.0.4
  cropperx: ^1.1.1

  just_audio: ^0.9.18
  record: ^3.0.2
  sign_in_with_apple: ^5.0.0

  video_trim: ^0.0.2
  photo_manager: ^3.0.0-dev.2
  preload_page_view: ^0.2.0

  extended_image: ^8.1.1
  photo_view: ^0.14.0
  zoom_pinch_overlay: ^1.2.0
  pinch_zoom: ^1.0.0
  pinch_zoom_image_last: ^0.4.1
  image_stack: ^2.1.1
  wakelock: ^0.6.2

  palette_generator: ^0.3.3+2
  image: ^4.0.17

  image_gallery_saver: ^2.0.1
  flutter_bloc: ^8.1.2

  google_fonts: ^4.0.4

  fluttericon: ^2.0.0
  page_transition: ^2.0.2
  path_provider: ^2.0.8
  expandable_text: ^2.3.0
  infinite_scroll_pagination: ^3.2.0

  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_svg: ^2.0.4
  flutter_spinkit: ^5.0.0



  extended_wrap: ^0.1.0
  dotted_border: ^2.0.0

  iconsax: ^0.0.8
  sizer: ^2.0.15
  email_validator: ^2.0.1
  pull_to_refresh: ^2.0.0
  flutter_fadein: ^2.0.0
  number_display: ^3.0.0
  timeago: ^3.0.2
  modal_bottom_sheet: ^2.0.0
  #  money2: ^2.3.0
  money2: ^3.4.1
  material_design_icons_flutter: ^5.0.6295
  badges: ^2.0.1
  flutter_slidable: ^1.1.0
  flutter_rating_bar: ^4.0.0
  shimmer: ^3.0.0
  align_positioned: ^3.0.0
  pattern_formatter: ^3.0.0
  searchfield: ^0.5.6
  flutter_typeahead: ^3.2.4
  #flutter_typeahead: ^4.0.0
  loading_indicator: ^3.0.2
  hive: ^2.0.5
  encrypt: ^5.0.1
  hive_flutter: ^1.1.0
  async: ^2.8.1
  grouped_list: ^5.1.1
  timezone: ^0.9.1
  #  calendar_time: ^2.2.0
  connectivity_plus: ^4.0.0

  flutter_staggered_grid_view: ^0.6.0
  http: ^1.0.0
  equatable: ^2.0.5
  geoflutterfire2: ^2.3.14
  google_maps_flutter: ^2.1.1

  geolocator: ^10.1.0
  geocoding: ^2.0.2
  uuid: ^3.0.5
  typesense: ^0.4.0
  tab_indicator_styler: ^2.0.0

  step_progress_indicator: ^1.0.2

  permission_handler: ^9.2.0

  scrollable_positioned_list: ^0.2.3
  map_launcher: ^2.2.1+2
  buttons_tabbar: ^1.3.4
  mime: ^1.0.1
  #  screen_recorder: ^0.0.3
  validators: ^3.0.0
  rxdart: ^0.27.4
  open_mail_app: ^0.4.5
  custom_refresh_indicator: ^1.2.1


  like_button: ^2.0.4
  flutter_keyboard_visibility: ^5.2.0
  flutter_emoji: ^2.4.0
  expandable: ^5.0.1
  flutter_phone_direct_caller: ^2.1.1
  url_launcher: ^6.1.5
  #  flutter_native_splash: ^2.2.9
  flutter_native_splash: ^2.3.2
  envied: ^0.5.2
  info_popup: ^3.0.0
  im_stepper: ^1.0.1+1
  animated_emoji: ^1.0.1+2

  #  appinio_social_share: ^0.2.1
  appinio_social_share: ^0.2.6
  loading_animation_widget: ^1.2.0+4

  #TODO: try photox
  photox: ^0.1.0
  photo_view_x: ^0.0.2
  easy_image_viewer: ^1.2.0
  #  wechat_camera_picker: ^3.8.0
  wechat_camera_picker: ^4.0.2
  wechat_assets_picker: ^8.8.0
  #  wechat_camera_picker: ^3.4.0
  #  sliver_tools: ^0.2.10
  sliver_tools: ^0.2.12
  device_info_plus: ^9.0.3
  posthog_flutter: ^3.1.0
  #  onfido_sdk: ^4.0.0
  #
  wolt_modal_sheet: ^0.2.0
  sliding_sheet2: ^2.0.1
  location: ^5.0.0
  jiffy: ^6.2.2
  fluro: ^2.0.5




  flutter_localizations:
    sdk: flutter


dependency_overrides:
  win32: 3.1.4
  intl: ^0.18.1

dev_dependencies:
  #  icons_launcher: ^1.1.9
  flutter_test:
    sdk: flutter
  envied_generator: ^0.5.2
  build_runner: ^2.4.6

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/launcher/skibble_app_icon.png"
  image_path_ios: "assets/launcher/skibble_app_icon_ios.png"
  adaptive_icon_background: "assets/launcher/skibble_icon_background.png"
  adaptive_icon_foreground: "assets/launcher/skibble_icon_foreground.png"

flutter_native_splash:
  color: "#00BF6D"
  image: "assets/images/skibble_letter_icon_white_434.png"

  android_12:
  #    image: "assets/launcher/skibble_icon_foreground.png"
  #    image: "assets/images/Skibble-icon-640px.png"
  #    image: "assets/images/Skibble-icon-white96 px.png"
  ##    image: "assets/images/skibble_splash_screen_image_720x720.png"
  ##    image: "assets/images/skibble_letter_icon_white_725x960.png"
  ##    image: "assets/images/skibble_letter_icon_white_73x96.png"
  #    image: "assets/images/skibble_letter_icon_white_10%.png"

  #    color: "#00BF6D"


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

#flutter_intl:                                   # Add this line
#  enabled: true                                 # Add this line
#  class_name: I10n                              # Add this line
#  main_locale: en                               # Add this line
#  arb_dir: lib/localization/l10n           # Add this line
#  output_dir: lib/localization/generated   # Add this line

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/custom_icons/
    - assets/launcher/
    - assets/animated_images/
    - assets/map_styles/
    - assets/sounds/
    - assets/languages/
    - assets/licenses/
    - assets/message.json
    - assets/images/yelp_assets/
  #    - .env.development
  #    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SkibbleIcons
      fonts:
        - asset: assets/fonts/SkibbleIcons.ttf

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

    - family: SkibbleCustomIcons
      fonts:
        - asset: assets/fonts/SkibbleCustomIcons.ttf

    - family: ChefIcons
      fonts:
        - asset: assets/fonts/ChefIcons.ttf

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
